// Minimal provider-agnostic interface. Agent-core only depends on this and doesn't care whether it's OpenAI or anything else.
export type Role = "system" | "user" | "assistant";

export interface ChatMessage {
  role: Role;
  content: string;
}

// Structured output (used by the tutor agent): name + JSON schema (generated by zod-to-json-schema).
export interface JsonSchemaSpec {
  name: string;
  schema: Record<string, unknown>;
}

export type FinishReasonKind =
  | "stop"
  | "length"
  | "content_filter"
  | "tool_use"
  | "other";

export interface FinishReason {
  kind: FinishReasonKind;
  raw: string;
  provider: "openai" | "anthropic" | "gemini";
}

// Token usage reported by the provider for a request. inputTokens is the real prompt size (the full context the
// model billed, including any cached prefix); it refines the UI context-usage meter over the local estimate.
export interface Usage {
  inputTokens?: number;
  outputTokens?: number;
}

export interface GenerateOptions {
  messages: ChatMessage[];
  temperature?: number;
  /** Maximum output tokens for non-streaming generation (≥2048 recommended for structured tasks like the tutor). */
  maxTokens?: number;
  jsonSchema?: JsonSchemaSpec;
  /** Simple JSON mode (response_format: json_object), for compatibility with endpoints that don't support json_schema. */
  jsonObject?: boolean;
  /** Non-functional metadata (for plugins, e.g. log labeling to distinguish which agent is calling). Ignored by the provider itself. */
  meta?: { label?: string };
  /** Finish reason returned by the provider; used to detect max_tokens truncation and similar. */
  onFinish?: (reason: FinishReason) => void;
  /** Token usage reported by the provider when available; inputTokens is the real prompt size for the UI meter.
   *  Not all endpoints report usage (e.g. some OpenAI-compatible servers) — callers fall back to the estimate. */
  onUsage?: (usage: Usage) => void;
}

export interface ModelProvider {
  generate(opts: GenerateOptions): Promise<string>;
  stream(
    opts: GenerateOptions,
    onDelta: (delta: string) => void,
  ): Promise<string>;
}
